name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential -y
        sudo apt-get install libgtest-dev -y
        sudo apt-get install cmake -y
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
    - name: run
      run: |
        cd
        sudo make
        sudo ./bmicalculator
        
